name: Enforce Changelog
on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Changelog
        run: |
          git diff $TARGET_BRANCH $BASE_BRANCH --quiet -- changelog.txt; nochanges=$?
          if [ $nochanges -eq 0 ]; then
                exit 1
          else
                exit 0
          fi
        env:
         BASE_BRANCH: ${{ github.base_ref }}
         TARGET_BRANCH: ${{ github.head_ref }}
