name: Enforce Changelog
on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 
      - name: Check Changelog
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git diff origin/$BASE_BRANCH origin/$TARGET_BRANCH -- changelog.txt
          git diff origin/$BASE_BRANCH origin/$TARGET_BRANCH --quiet -- changelog.txt; nochanges=$?
          echo $nochanges
          if [ $nochanges -eq 0 ]; then
                exit 1
          else
                exit 0
          fi
        env:
         BASE_BRANCH: ${{ github.base_ref }}
         TARGET_BRANCH:  ${{ github.head_ref }}
